name: Build and deploy Flutter Web App to Azure Web App

on:
  push:
    branches:
      - flutterflow
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_44965F1672294D609C9A93F390C2F4FA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D857756EFC8846F78C450AFA93C23BB1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6414FC64AF43499DB1A9AEB3FF956DA5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pexel-flutterflow-app'
          slot-name: 'Production'
          package: './build/web'

